/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WorkerRouteImport } from './routes/worker'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ClientRouteImport } from './routes/client'
import { Route as BookRouteImport } from './routes/book'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkerIndexRouteImport } from './routes/worker.index'
import { Route as ClientIndexRouteImport } from './routes/client.index'
import { Route as WorkerTaskIdRouteImport } from './routes/worker.$taskId'
import { Route as ServicesSlugRouteImport } from './routes/services_.$slug'
import { Route as ClientTaskIdRouteImport } from './routes/client.$taskId'
import { Route as AdminWorkersRouteImport } from './routes/admin.workers'
import { Route as AdminTasksRouteImport } from './routes/admin.tasks'
import { Route as AdminSlaRouteImport } from './routes/admin.sla'
import { Route as AdminLiveRouteImport } from './routes/admin.live'

const WorkerRoute = WorkerRouteImport.update({
  id: '/worker',
  path: '/worker',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientRoute = ClientRouteImport.update({
  id: '/client',
  path: '/client',
  getParentRoute: () => rootRouteImport,
} as any)
const BookRoute = BookRouteImport.update({
  id: '/book',
  path: '/book',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkerIndexRoute = WorkerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => WorkerRoute,
} as any)
const ClientIndexRoute = ClientIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ClientRoute,
} as any)
const WorkerTaskIdRoute = WorkerTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => WorkerRoute,
} as any)
const ServicesSlugRoute = ServicesSlugRouteImport.update({
  id: '/services_/$slug',
  path: '/services/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientTaskIdRoute = ClientTaskIdRouteImport.update({
  id: '/$taskId',
  path: '/$taskId',
  getParentRoute: () => ClientRoute,
} as any)
const AdminWorkersRoute = AdminWorkersRouteImport.update({
  id: '/workers',
  path: '/workers',
  getParentRoute: () => AdminRoute,
} as any)
const AdminTasksRoute = AdminTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AdminRoute,
} as any)
const AdminSlaRoute = AdminSlaRouteImport.update({
  id: '/sla',
  path: '/sla',
  getParentRoute: () => AdminRoute,
} as any)
const AdminLiveRoute = AdminLiveRouteImport.update({
  id: '/live',
  path: '/live',
  getParentRoute: () => AdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/worker': typeof WorkerRouteWithChildren
  '/admin/live': typeof AdminLiveRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/client/$taskId': typeof ClientTaskIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/worker/$taskId': typeof WorkerTaskIdRoute
  '/client/': typeof ClientIndexRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/admin/live': typeof AdminLiveRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/client/$taskId': typeof ClientTaskIdRoute
  '/services/$slug': typeof ServicesSlugRoute
  '/worker/$taskId': typeof WorkerTaskIdRoute
  '/client': typeof ClientIndexRoute
  '/worker': typeof WorkerIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRouteWithChildren
  '/auth': typeof AuthRoute
  '/book': typeof BookRoute
  '/client': typeof ClientRouteWithChildren
  '/contact': typeof ContactRoute
  '/pricing': typeof PricingRoute
  '/reviews': typeof ReviewsRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/services': typeof ServicesRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/worker': typeof WorkerRouteWithChildren
  '/admin/live': typeof AdminLiveRoute
  '/admin/sla': typeof AdminSlaRoute
  '/admin/tasks': typeof AdminTasksRoute
  '/admin/workers': typeof AdminWorkersRoute
  '/client/$taskId': typeof ClientTaskIdRoute
  '/services_/$slug': typeof ServicesSlugRoute
  '/worker/$taskId': typeof WorkerTaskIdRoute
  '/client/': typeof ClientIndexRoute
  '/worker/': typeof WorkerIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book'
    | '/client'
    | '/contact'
    | '/pricing'
    | '/reviews'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/worker'
    | '/admin/live'
    | '/admin/sla'
    | '/admin/tasks'
    | '/admin/workers'
    | '/client/$taskId'
    | '/services/$slug'
    | '/worker/$taskId'
    | '/client/'
    | '/worker/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book'
    | '/contact'
    | '/pricing'
    | '/reviews'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/admin/live'
    | '/admin/sla'
    | '/admin/tasks'
    | '/admin/workers'
    | '/client/$taskId'
    | '/services/$slug'
    | '/worker/$taskId'
    | '/client'
    | '/worker'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/auth'
    | '/book'
    | '/client'
    | '/contact'
    | '/pricing'
    | '/reviews'
    | '/robots.txt'
    | '/services'
    | '/sitemap.xml'
    | '/worker'
    | '/admin/live'
    | '/admin/sla'
    | '/admin/tasks'
    | '/admin/workers'
    | '/client/$taskId'
    | '/services_/$slug'
    | '/worker/$taskId'
    | '/client/'
    | '/worker/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRouteWithChildren
  AuthRoute: typeof AuthRoute
  BookRoute: typeof BookRoute
  ClientRoute: typeof ClientRouteWithChildren
  ContactRoute: typeof ContactRoute
  PricingRoute: typeof PricingRoute
  ReviewsRoute: typeof ReviewsRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  ServicesRoute: typeof ServicesRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  WorkerRoute: typeof WorkerRouteWithChildren
  ServicesSlugRoute: typeof ServicesSlugRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/worker': {
      id: '/worker'
      path: '/worker'
      fullPath: '/worker'
      preLoaderRoute: typeof WorkerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client': {
      id: '/client'
      path: '/client'
      fullPath: '/client'
      preLoaderRoute: typeof ClientRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/book': {
      id: '/book'
      path: '/book'
      fullPath: '/book'
      preLoaderRoute: typeof BookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/worker/': {
      id: '/worker/'
      path: '/'
      fullPath: '/worker/'
      preLoaderRoute: typeof WorkerIndexRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/client/': {
      id: '/client/'
      path: '/'
      fullPath: '/client/'
      preLoaderRoute: typeof ClientIndexRouteImport
      parentRoute: typeof ClientRoute
    }
    '/worker/$taskId': {
      id: '/worker/$taskId'
      path: '/$taskId'
      fullPath: '/worker/$taskId'
      preLoaderRoute: typeof WorkerTaskIdRouteImport
      parentRoute: typeof WorkerRoute
    }
    '/services_/$slug': {
      id: '/services_/$slug'
      path: '/services/$slug'
      fullPath: '/services/$slug'
      preLoaderRoute: typeof ServicesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/$taskId': {
      id: '/client/$taskId'
      path: '/$taskId'
      fullPath: '/client/$taskId'
      preLoaderRoute: typeof ClientTaskIdRouteImport
      parentRoute: typeof ClientRoute
    }
    '/admin/workers': {
      id: '/admin/workers'
      path: '/workers'
      fullPath: '/admin/workers'
      preLoaderRoute: typeof AdminWorkersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tasks': {
      id: '/admin/tasks'
      path: '/tasks'
      fullPath: '/admin/tasks'
      preLoaderRoute: typeof AdminTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sla': {
      id: '/admin/sla'
      path: '/sla'
      fullPath: '/admin/sla'
      preLoaderRoute: typeof AdminSlaRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/live': {
      id: '/admin/live'
      path: '/live'
      fullPath: '/admin/live'
      preLoaderRoute: typeof AdminLiveRouteImport
      parentRoute: typeof AdminRoute
    }
  }
}

interface AdminRouteChildren {
  AdminLiveRoute: typeof AdminLiveRoute
  AdminSlaRoute: typeof AdminSlaRoute
  AdminTasksRoute: typeof AdminTasksRoute
  AdminWorkersRoute: typeof AdminWorkersRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminLiveRoute: AdminLiveRoute,
  AdminSlaRoute: AdminSlaRoute,
  AdminTasksRoute: AdminTasksRoute,
  AdminWorkersRoute: AdminWorkersRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

interface ClientRouteChildren {
  ClientTaskIdRoute: typeof ClientTaskIdRoute
  ClientIndexRoute: typeof ClientIndexRoute
}

const ClientRouteChildren: ClientRouteChildren = {
  ClientTaskIdRoute: ClientTaskIdRoute,
  ClientIndexRoute: ClientIndexRoute,
}

const ClientRouteWithChildren =
  ClientRoute._addFileChildren(ClientRouteChildren)

interface WorkerRouteChildren {
  WorkerTaskIdRoute: typeof WorkerTaskIdRoute
  WorkerIndexRoute: typeof WorkerIndexRoute
}

const WorkerRouteChildren: WorkerRouteChildren = {
  WorkerTaskIdRoute: WorkerTaskIdRoute,
  WorkerIndexRoute: WorkerIndexRoute,
}

const WorkerRouteWithChildren =
  WorkerRoute._addFileChildren(WorkerRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRouteWithChildren,
  AuthRoute: AuthRoute,
  BookRoute: BookRoute,
  ClientRoute: ClientRouteWithChildren,
  ContactRoute: ContactRoute,
  PricingRoute: PricingRoute,
  ReviewsRoute: ReviewsRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  ServicesRoute: ServicesRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  WorkerRoute: WorkerRouteWithChildren,
  ServicesSlugRoute: ServicesSlugRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
